Error: SYMBIOTIC_WARNING:
libffi-3.1/testsuite/libffi.call/pyobjc-tc.c:33: error: memory error: memory leak detected
libffi-3.1/testsuite/libffi.call/pyobjc-tc.c:33: note: call stack: function main ()
libffi-3.1/testsuite/libffi.call/pyobjc-tc.c:33: note: Additional Info: address: 43:0
libffi-3.1/testsuite/libffi.call/pyobjc-tc.c:33: note: Additional Info: pointing to: object at Segment: [43] of size 24
libffi-3.1/testsuite/libffi.call/pyobjc-tc.c:33: note: Additional Info: MO32[24] allocated at main():  %22 = call noalias align 16 i8* @malloc(i64 24) #6, !dbg !79
libffi-3.1/testsuite/libffi.call/pyobjc-tc.c:81:6: note: Non-deterministic values: ffi_prep_cif: len 4 bytes, [0x1|3 times 0x0] (i32: 1)
#   31|   
#   32|   
#   33|-> int main(void)
#   34|   {
#   35|   	ffi_type point_type;

Error: SYMBIOTIC_WARNING:
libffi-3.1/testsuite/libffi.call/pyobjc-tc.c:113: error: memory error: memory leak detected
libffi-3.1/testsuite/libffi.call/pyobjc-tc.c:113: note: call stack: function main ()
libffi-3.1/testsuite/libffi.call/pyobjc-tc.c:113: note: Additional Info: address: 43:0
libffi-3.1/testsuite/libffi.call/pyobjc-tc.c:113: note: Additional Info: pointing to: object at Segment: [43] of size 24
libffi-3.1/testsuite/libffi.call/pyobjc-tc.c:113: note: Additional Info: MO32[24] allocated at main():  %22 = call noalias align 16 i8* @malloc(i64 24) #6, !dbg !79
libffi-3.1/testsuite/libffi.call/pyobjc-tc.c:81:6: note: Non-deterministic values: ffi_prep_cif: len 4 bytes, [4 times 0x0] (i32: 0)
#  111|   
#  112|   	}
#  113|-> 	exit(0);
#  114|   }
